package com.wutianyi.study.ibatis.dataobject;

public class Test1 {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_1.id
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_1.t
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    private String t;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_1.id
     *
     * @return the value of test_1.id
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_1.id
     *
     * @param id the value for test_1.id
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_1.t
     *
     * @return the value of test_1.t
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    public String getT() {
        return t;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_1.t
     *
     * @param t the value for test_1.t
     *
     * @abatorgenerated Tue Apr 12 02:24:39 CST 2011
     */
    public void setT(String t) {
        this.t = t;
    }
}