package com.wutianyi.logger.dataobject;

import java.util.Date;

public class LoggerDO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.id
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.gmt_create
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private Date gmtCreate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.gmt_modified
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private Date gmtModified;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.old_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private String oldValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.new_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private String newValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.operation_type
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private String operationType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logger.operator
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    private String operator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.id
     *
     * @return the value of logger.id
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.id
     *
     * @param id the value for logger.id
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.gmt_create
     *
     * @return the value of logger.gmt_create
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.gmt_create
     *
     * @param gmtCreate the value for logger.gmt_create
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.gmt_modified
     *
     * @return the value of logger.gmt_modified
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.gmt_modified
     *
     * @param gmtModified the value for logger.gmt_modified
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.old_value
     *
     * @return the value of logger.old_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.old_value
     *
     * @param oldValue the value for logger.old_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.new_value
     *
     * @return the value of logger.new_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.new_value
     *
     * @param newValue the value for logger.new_value
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.operation_type
     *
     * @return the value of logger.operation_type
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.operation_type
     *
     * @param operationType the value for logger.operation_type
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logger.operator
     *
     * @return the value of logger.operator
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logger.operator
     *
     * @param operator the value for logger.operator
     *
     * @abatorgenerated Mon Apr 18 10:49:55 CST 2011
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}