package com.wutianyi.study.ibatis.dao;

import java.util.List;

import com.wutianyi.study.ibatis.dataobject.Test1;
import com.wutianyi.study.ibatis.dataobject.Test1Example;

public interface Test1DAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    void insert(String record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    int updateByPrimaryKey(Test1 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    int updateByPrimaryKeySelective(Test1 record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    List selectByExample(Test1Example example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    List selectByExample(Test1Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    Test1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    int deleteByExample(Test1Example example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table test_1
     *
     * @abatorgenerated Tue Apr 12 02:22:57 CST 2011
     */
    int deleteByPrimaryKey(Integer id);
}